settings:
    react:
        version: detect
env:
    es6: true
parser: "@typescript-eslint/parser"
plugins:
    - "eslint-plugin-react"
    - "@typescript-eslint"
rules:
    # React rules
    react/jsx-fragments:
        - error
        - syntax
    react/jsx-uses-react: error
    react/jsx-uses-vars: error
    react/no-did-mount-set-state: error
    react/no-did-update-set-state: error
    react/no-direct-mutation-state: error
    react/no-this-in-sfc: error
    # react/self-closing-comp: error
    react/react-in-jsx-scope: error
    # General rules
    arrow-body-style: error
    camelcase: error
    class-methods-use-this: error
    constructor-super: error
    dot-notation: error
    lines-between-class-members: error
    no-case-declarations: error
    no-cond-assign: error
    no-constant-condition: error
    no-debugger: error
    no-dupe-args: error
    no-dupe-class-members: error
    no-dupe-keys: error
    no-duplicate-case: error
    no-duplicate-imports: error
    no-empty: error
    no-empty-character-class: error
    no-empty-function: error
    no-empty-pattern: error
    no-eval: error
    no-extra-boolean-cast: error
    no-extra-parens: error
    no-fallthrough: error
    no-func-assign: error
    no-implied-eval: error
    no-inner-declarations: error
    no-invalid-this: error
    no-irregular-whitespace: error
    no-label-var: error
    no-lonely-if: error
    no-misleading-character-class: error
    no-multi-str: error
    no-new-symbol: error
    no-octal: error
    no-redeclare: error
    no-return-assign: error
    no-return-await: error
    no-self-compare: error
    no-sequences: error
    no-shadow-restricted-names: error
    no-sparse-arrays: error
    no-template-curly-in-string: error
    no-this-before-super: error
    no-trailing-spaces: error
    no-undef-init: error
    no-undefined: error
    no-unexpected-multiline: error
    no-unreachable: error
    no-unused-vars: warn
    no-useless-computed-key: error
    no-useless-concat: error
    no-useless-escape: error
    no-useless-rename: error
    no-useless-return: error
    no-var: error
    no-warning-comments: error
    no-with: error
    object-curly-newline: error
    object-curly-spacing:
        - error
        - always
    one-var:
        - error
        - never
    operator-assignment: error
    operator-linebreak:
        - error
        - before
    padded-blocks:
        - error
        - never
    prefer-arrow-callback: error
    prefer-const: error
    prefer-numeric-literals: error
    prefer-object-spread: error
    prefer-rest-params: error
    prefer-template: error
    quotes:
        - error
        - single
        - allowTemplateLiterals: true
    require-await: error
    require-yield: error
    space-before-function-paren:
        - error
        - anonymous: always
          asyncArrow: always
          named: never
    symbol-description: error
    template-tag-spacing: error
    valid-typeof: error
    yoda: error
