name: main

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - run: yarn
            - run: yarn prettier --ignore-path .gitignore --check .

            - run: yarn build:telescope
            - run: yarn build:observatory
            - run: yarn workspace observatory type-check
            - run: yarn workspace observatory lint
            # - run: yarn workspace observatory test

    package:
        strategy:
            matrix:
                platform: [macos-latest, ubuntu-latest, windows-latest]

        runs-on: ${{ matrix.platform }}

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - run: yarn

            # Platform specific shenanigans
            - run: yarn workspace observatory configure -y
              if: ${{ matrix.platform != 'windows-latest' }}
            - run: yarn workspace observatory configure-win -y
              if: ${{ matrix.platform == 'windows-latest' }}

            - run: yarn build:telescope
            - run: yarn workspace observatory forge

            - run: ls packages/observatory/out
            - run: ls packages/observatory/out/make

            # - name: Upload produced installer
            #   uses: actions/upload-artifact@v2
            #   with:
            #       name: code-coverage-report
            #       path: out/make/*.dmg
