name: main

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - run: npm i -g npm@latest

            - run: npm install
            - run: npx prettier --ignore-path .gitignore --check .

            - run: npm run build:telescope
            - run: npm run build:observatory
            - run: npm run type-check -w observatory
            - run: npm run lint -w observatory
            # - run: yarn workspace observatory test

    package:
        strategy:
            matrix:
                platform: [macos-latest, ubuntu-latest, windows-latest]
            fail-fast: false

        runs-on: ${{ matrix.platform }}

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - run: npm i -g npm@latest

            - run: npm install

            # Platform specific shenanigans
            - run: npm run configure -w observatory

            - run: npm run build:telescope
            - run: npm run forge -w observatory

            - name: Upload Windows x64 installer
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.platform }}
                  path: packages/observatory/out/make/squirrel.windows/x64
              if: ${{ matrix.platform == 'windows-latest' }}

            - name: Upload Linux x64 zip
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.platform }}
                  path: packages/observatory/out/make/zip/linux/x64
              if: ${{ matrix.platform == 'ubuntu-latest' }}

            - name: Upload macOS x64 dmg
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.platform }}
                  path: packages/observatory/out/make/*.dmg
              if: ${{ matrix.platform == 'macos-latest' }}
