name: main

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - run: yarn
            - run: yarn prettier --ignore-path .gitignore --check .

            - run: which cargo
            - run: cargo -V
            - run: echo $PATH
            - run: node -v
            - run: yarn -v
            - run: yarn neon version
            - run: yarn electron-build-env -V

            - run: yarn global add neon-cli

            - run: yarn electron-build-env \"echo $PATH\"
            - run: yarn electron-build-env \"yarn neon version\"

            - run: cd packages/telescope && yarn neon build

            - run: yarn workspace observatory build
            - run: yarn workspace observatory type-check
            # - run: yarn workspace observatory lint
            # - run: yarn workspace observatory test
